name: release

on:
  release:
    types: [created, edited]

jobs:
  build-and-publish:
    name: Build and publish Python distributions PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install pypa/build
        run: |
          make build-dependencies

      - name: Build a binary wheel and a source tarball
        run: |
          make build

      - name: Publish distribution package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
